### ISSUE TITLE
Randomly installs classic versions

### ISSUE THREAD

**Issue by zerodogg** [ephraim/lcurse#79]
Using the latest version of lcurse it is randomly chosing to install "classic" versions of mods rather than the live versions. It has done this to, among others, AdvancedInterfaceOptions, DBM Voicepack VEM, Details! Damage Meter, GTFO and Prat 3.0

**Comment by torkus** [comment]
hi, not a maintainer of lcurse, but the issue lies about here:
https://github.com/ephraim/lcurse/blob/4a22aa1607ddce818bf0a4d69f31d5fef160601b/modules/waitdlg.py#L192-L201

it's because curseforge relatively recently allowed 'classic' releases of their addons, as well as alpha/beta/alternate releases that lcurse already seems to do.

This is really bad form on my part, but there are other addon managers that support classic here: https://github.com/ogri-la/wowman#other-addon-managers

**Comment by timwienk** [comment]
I do have it working in my version, I PR'ed my changes in #80 in case that helps.

**Comment by timwienk** [comment]
Since #80 is merged, I think this is solved and can be closed.

**Comment by torkus** [comment]
I've taken a look at the code changes and read the commit messages and I'm still not clear on whether lcurse actually supports the installation of classic addons from curseforge or is just ignoring them ... I ask because [my data may be wrong](https://ogri-la.github.io/wow-addon-managers/?preset/name=unfiltered&field/maintained=&field/windows=&field/eula=&field/ads=&field/source-available=yes&field/ui=GUI&field/language=&field/retail=&field/linux=yes*&field/f-oss=no&field/classic=no&field/mac=) ;)

**Comment by timwienk** [comment]
It supports Classic as well. It should even work for PTR as well, provided if it's installed in the same WoW directory.

- [supported WoW folders/directories](https://github.com/ephraim/lcurse/blob/master/modules/application.py#L248L255): retail, classic, ptr
- [separate addon JSON files](https://github.com/ephraim/lcurse/blob/master/modules/application.py#L264L267): `addons.json`, `addons_classic.json`, `addons_ptr.json`
- [code that tries to find the right addon version](https://github.com/ephraim/lcurse/blob/master/modules/waitdlg.py#L195L211):
  * when installing for WoW Retail, it skips Classic addons
  * when installing for WoW Classic, it allows Retail addons when there is no Classic version of the addon
  * figuring out whether an addon is for Retail or Classic, is done in a bit of a naive way, but it works in practice: basically the addon should support either `1.x` for Classic or `8.x` or higher for Retail, or support multiple versions (= contain a `+` in the supported versions)
